
# begin common build properties
# autogenerated by build/make/tools/buildinfo_common.sh
ro.system.build.date=Thu Mar 17 02:22:46 UTC 2022
ro.system.build.date.utc=1647483766
ro.system.build.fingerprint=google/coral/coral:11/RQ3A.210905.001/7511028:user/release-keys
ro.system.build.id=RQ3A.211001.001
ro.system.build.tags=release-keys
ro.system.build.type=user
ro.system.build.version.incremental=eng.rehan.20220317.022248
ro.system.build.version.release=11
ro.system.build.version.release_or_codename=11
ro.system.build.version.sdk=30
ro.product.system.brand=Realme
ro.product.system.device=RMX1821
ro.product.system.manufacturer=Realme
ro.product.system.model=RMX1821
ro.product.system.name=lineage_RMX1821
# end common build properties
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=RQ3A.211001.001
ro.build.display.id=RQ3A.211001.001 release-keys
ro.build.version.incremental=eng.rehan.20220317.022248
ro.build.version.sdk=30
ro.build.version.preview_sdk=0
ro.build.version.preview_sdk_fingerprint=REL
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=11
ro.build.version.release_or_codename=11
ro.build.version.security_patch=2022-03-05
ro.build.version.base_os=
ro.build.version.min_supported_target_sdk=23
ro.build.date=Thu Mar 17 02:22:46 UTC 2022
ro.build.date.utc=1647483766
ro.build.type=user
ro.build.user=rehan
ro.build.host=build
ro.build.tags=release-keys
ro.build.flavor=lineage_RMX1821-user
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a
ro.product.locale=en-US
ro.wifi.channels=
# ro.build.product is obsolete; use ro.product.device
ro.build.product=RMX1821
# Do not try to parse description or thumbprint
ro.build.description=lineage_RMX1821-user 11 RQ3A.211001.001 eng.rehan.20220317.022248 release-keys
ro.lineage.device=RMX1821
# end build properties

#
# from device/realme/RMX1821/system.prop
#
#
# system.prop for Realme 3
#

# Surfaceflinger
debug.sf.enable_gl_backpressure=1
ro.surface_flinger.max_frame_buffer_acquired_buffers=3
ro.surface_flinger.vsync_event_phase_offset_ns=2000000
ro.surface_flinger.vsync_sf_event_phase_offset_ns=6000000
debug.sf.latch_unsignaled=1
debug.sf.early_app_phase_offset_ns=1500000
debug.sf.early_gl_phase_offset_ns=3000000
debug.sf.early_gl_app_phase_offset_ns=15000000
debug.sf.early_phase_offset_ns=1500000

rild.libpath=mtk-ril.so
rild.libargs=-d /dev/ttyC0


# MTK, Infinity, 20090720 {
wifi.interface=wlan0
# MTK, Infinity, 20090720 }

# MTK, mtk03034, 20101210 {
ro.mediatek.wlan.wsc=1
# MTK, mtk03034 20101210}
# MTK, mtk03034, 20110318 {
ro.mediatek.wlan.p2p=1
# MTK, mtk03034 20110318}

# MTK, mtk03034, 20101213 {
mediatek.wlan.ctia=0
# MTK, mtk03034 20101213}


#
wifi.tethering.interface=ap0
#

ro.opengles.version=196610
#ro.kernel.qemu=1
#ro.kernel.qemu.gles=0

wifi.direct.interface=p2p0
#dalvik.vm.heapgrowthlimit=256m
#dalvik.vm.heapsize=512m

# USB MTP WHQL
ro.sys.usb.mtp.whql.enable=0

# Power off opt in IPO
sys.ipo.pwrdncap=2

ro.sys.usb.storage.type=mtp

# USB BICR function
ro.sys.usb.bicr=no

# USB Charge only function
ro.sys.usb.charging.only=yes

# audio
ro.camera.sound.forced=0
ro.audio.silent=0

ro.zygote.preload.enable=0

# temporary enables NAV bar (soft keys)
qemu.hw.mainkeys=0

ro.kernel.zio=38,108,105,16
#ro.kernel.qemu=1
#ro.kernel.qemu.gles=0
#ro.boot.selinux=disable

# Disable dirty region for Mali
#debug.hwui.render_dirty_regions=false

#ifneq ($(strip $(ODM_HQ_EDIT)),yes)
#liyan@ODM.Multimedia.LCD  2018/10/03 add for LCD bring up
#ro.sf.lcd_density=480
#else #ODM_HQ_EDIT
#ro.sf.lcd_density=320
#endif #ODM_HQ_EDIT

# performance
ro.mtk_perf_simple_start_win=1
ro.mtk_perf_fast_start_win=1
ro.mtk_perf_response_time=1

# disable ipo for development
sys.ipo.disable=1

#ifdef VENDOR_EDIT
#Wensheng.Wang@PSW.AD.Stability.Compatibility,2018/11/27,Add coordinate property for application adaptation
ro.oppo.screen.heteromorphism=264,0:456,54

# IMS
persist.dbg.volte_avail_ovr=1
persist.dbg.vt_avail_ovr=1
persist.dbg.wfc_avail_ovr=1

# Charger
ro.charger.enable_suspend=true

# Tweak the memory management of the device, enable more background apps.. etc..
ro.config.fha_enable=true \
ro.sys.fw.bg_apps_limit=32 \
ro.config.dha_cached_max=16 \
ro.config.dha_empty_max=42 \
ro.config.dha_empty_init=32 \
ro.config.dha_lmk_scale=0.545 \
ro.config.dha_th_rate=2.3 \
ro.config.sdha_apps_bg_max=64 \
ro.config.sdha_apps_bg_min=8

#props:disable hwc_vds *to fix screen recording lags
debug.sf.enable_hwc_vds=0

# ZRAM
ro.zram.mark_idle_delay_mins=60
ro.zram.first_wb_delay_mins=1440
ro.zram.periodic_wb_delay_hours=24

# LMKD
ro.lmk.psi_complete_stall_ms=150
ro.lmk.swap_free_low_percentage=20
ro.lmk.kill_timeout_ms=100

# Dex2oat
dalvik.vm.dex2oat64.enabled=true
dalvik.vm.image-dex2oat-filter=quicken
dalvik.vm.image-dex2oat-threads=8
dalvik.vm.image-dex2oat-cpu-set=0,1,2,3,4,5,6,7
dalvik.vm.dex2oat-filter=quicken
dalvik.vm.dex2oat-threads=8
dalvik.vm.dex2oat-cpu-set=0,1,2,3,4,5,6,7
dalvik.vm.boot-dex2oat-threads=8
dalvik.vm.boot-dex2oat-cpu-set=0,1,2,3,4,5,6,7
# end of device/realme/RMX1821/system.prop

#
# ADDITIONAL_BUILD_PROPERTIES
#
keyguard.no_require_sim=true
ro.carrier=unknown
ro.services.whitelist.packagelist=com.google.android.gms
ro.iorapd.enable=true
iorapd.perfetto.enable=true
iorapd.readahead.enable=true
ro.apex.updatable=true
ro.treble.enabled=true
net.bt.name=Android
ro.build.fingerprint=google/coral/coral:11/RQ3A.210905.001/7511028:user/release-keys
ro.lineage.version=LineageFE-v11.69-20220317-RMX1821-Isobar
ro.lineage.display.version=11.69.-20220317-RMX1821
ro.lineage.build.version=11.69
ro.modversion=LineageFE-v11.69-20220317-RMX1821-Isobar
ro.lineage.build.version.plat.sdk=9
ro.lineage.build.version.plat.rev=0

# Touch
touch.pressure.scale=0.000
persist.sys.ui.hw=0
touch.size.calibration=diameter
touch.size.scale=0
touch.size.bias=0
touch.size.isSummed=0
touch.pressure.scale=0.000
touch.orientation.calibration=none
touch.distance.calibration=none
touch.distance.scale=0
touch.coverage.calibration=box
touch.gestureMode=spots
MultitouchSettleInterval=0.0ms
MultitouchMinDistance=0.0px
TapInterval=0.0ms
TapSlop=0.0px
